<<<<<<< HEAD
# Generated by Django 3.2.7 on 2022-04-08 06:41
=======
# Generated by Django 4.0.3 on 2022-04-08 05:31
>>>>>>> 3c8c858274347881ab6e0e59087e4fea704ae490

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('auth_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=30)),
=======
                ('book_name', models.CharField(max_length=32)),
                ('book_description', models.CharField(max_length=30)),
>>>>>>> 3c8c858274347881ab6e0e59087e4fea704ae490
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('book_name', models.CharField(max_length=32)),
                ('book_description', models.CharField(max_length=30)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.author')),
                ('cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.category')),
=======
                ('auth_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=30)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.book')),
>>>>>>> 3c8c858274347881ab6e0e59087e4fea704ae490
            ],
        ),
    ]
