# Generated by Django 3.2.7 on 2022-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='auth',
        ),
        migrations.AddField(
            model_name='book',
            name='auth',
            field=models.ManyToManyField(to='testapp.Author'),
        ),
    ]
