# Generated by Django 3.2.7 on 2022-04-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20220408_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='auth',
            field=models.ManyToManyField(related_name='all_authors', to='testapp.Author'),
        ),
    ]
