# Generated by Django 3.2.7 on 2022-04-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_book_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='auth',
            field=models.ManyToManyField(blank=True, related_name='all_authors', to='testapp.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
